"""Regenerate app/tools/universe_constituents.py from Wikipedia.

Fetches the current S&P 500 and S&P/TSX 60 constituent lists and rewrites the
generated module in Yahoo Finance symbol format (class shares ``BRK.B`` ->
``BRK-B``; TSX listings suffixed ``.TO``, e.g. ``CCL.B`` -> ``CCL-B.TO``).

Run manually (roughly quarterly — index turnover is slow, and the screener
tolerates dead tickers via the fundamentals error rows):

    .venv/bin/python scripts/refresh_universe.py

The rewritten module's git diff is the review.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

import requests
from bs4 import BeautifulSoup

SP500_URL = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
TSX60_URL = "https://en.wikipedia.org/wiki/S%26P/TSX_60"
_HEADERS = {"User-Agent": "cirvia-universe-refresh/1.0 (+https://cirvia.ca)"}

OUT_PATH = Path(__file__).resolve().parents[1] / "app" / "tools" / "universe_constituents.py"

# Sanity bounds: a parse that lands outside these is a page-layout change,
# not an index change — fail loudly rather than write a truncated universe.
SP500_BOUNDS = (490, 520)
TSX60_BOUNDS = (55, 65)


def _fetch_soup(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=_HEADERS, timeout=30)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def _symbol_cells(soup: BeautifulSoup, *, symbol_header: str) -> list[str]:
    """Extract the symbol column from the first wikitable whose header row
    contains ``symbol_header`` (case-insensitive)."""
    for table in soup.find_all("table", class_="wikitable"):
        header_row = table.find("tr")
        if header_row is None:
            continue
        headers = [th.get_text(strip=True).lower() for th in header_row.find_all("th")]
        if symbol_header not in headers:
            continue
        col = headers.index(symbol_header)
        symbols: list[str] = []
        for row in table.find_all("tr")[1:]:
            cells = row.find_all(["td", "th"])
            if len(cells) <= col:
                continue
            text = cells[col].get_text(strip=True)
            if text:
                symbols.append(text)
        if symbols:
            return symbols
    raise RuntimeError(f"no wikitable with a '{symbol_header}' column found")


def to_yahoo_us(symbol: str) -> str:
    """US listing to Yahoo format: class-share dots become hyphens."""
    return symbol.strip().upper().replace(".", "-")


def to_yahoo_tsx(symbol: str) -> str:
    """TSX listing to Yahoo format: dots become hyphens, ``.TO`` suffix added."""
    s = symbol.strip().upper()
    if s.endswith(".TO"):
        s = s[: -len(".TO")]
    return s.replace(".", "-") + ".TO"


def _dedup(symbols: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for s in symbols:
        if s not in seen:
            seen.add(s)
            out.append(s)
    return out


def _check_bounds(name: str, symbols: list[str], bounds: tuple[int, int]) -> None:
    lo, hi = bounds
    if not (lo <= len(symbols) <= hi):
        raise RuntimeError(f"{name}: parsed {len(symbols)} symbols, expected {lo}-{hi}")


def _render(sp500: list[str], tsx60: list[str], as_of: str) -> str:
    def block(names: list[str]) -> str:
        return "\n".join(f'    "{t}",' for t in names)

    return f'''"""Index constituent lists in Yahoo Finance symbol format.

Generated by scripts/refresh_universe.py — do not hand-edit.
Refresh roughly quarterly; the git diff is the review.
"""

AS_OF = "{as_of}"

SP500: list[str] = [
{block(sp500)}
]

TSX60: list[str] = [
{block(tsx60)}
]
'''


def main() -> int:
    sp500 = _dedup([to_yahoo_us(s) for s in _symbol_cells(_fetch_soup(SP500_URL), symbol_header="symbol")])
    tsx60 = _dedup([to_yahoo_tsx(s) for s in _symbol_cells(_fetch_soup(TSX60_URL), symbol_header="symbol")])
    _check_bounds("SP500", sp500, SP500_BOUNDS)
    _check_bounds("TSX60", tsx60, TSX60_BOUNDS)
    OUT_PATH.write_text(_render(sp500, tsx60, date.today().isoformat()))
    print(f"wrote {OUT_PATH} — SP500={len(sp500)} TSX60={len(tsx60)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
